// <auto-generated />
// 本文件由 T4 模板自动生成，请勿手动修改。
// 如果新增了 DTO，请右键点击 JsonContext.tt 选择 "运行自定义工具"。

using System.Text.Json.Serialization;

namespace OrderDispatch.WebApi
{
    [JsonSerializable(typeof(global::OrderDispatch.WebApi.Models.DTOs.BusinessDto[]))]
    [JsonSerializable(typeof(global::OrderDispatch.WebApi.Models.DTOs.OrderBasicInfoDto[]))]
    [JsonSerializable(typeof(global::OrderDispatch.WebApi.Models.DTOs.OrderCustomerInfoDto[]))]
    [JsonSerializable(typeof(global::OrderDispatch.WebApi.Models.DTOs.OrderDeliveryInfoDto[]))]
    [JsonSerializable(typeof(global::OrderDispatch.WebApi.Models.DTOs.OrderDto[]))]
    [JsonSerializable(typeof(global::OrderDispatch.WebApi.Models.DTOs.OrderItemDto[]))]
    [JsonSerializable(typeof(global::OrderDispatch.WebApi.Models.DTOs.RiderDto[]))]
    internal partial class AppJsonSerializerContext : JsonSerializerContext
    {
    }
}