@OrderDispatch.WebApi_HostAddress = http://localhost:5095

GET {{OrderDispatch.WebApi_HostAddress}}/todoitems/
Accept: application/json

###

GET {{OrderDispatch.WebApi_HostAddress}}/todoitems/1
Accept: application/json

###
